server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.204.188.249:3306/datinghub?serverTimezone=GMT%2b8
    username: xiaoxin
    password: DGYdgy130062
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 3034507585@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: dmyawkdehlxqdcfa
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl